### ISSUE TITLE
Subgraph Timed Out and Milestones not updating in UI

### ISSUE THREAD

**Issue by boilerrat** [DAOmasons/grant-ships-app#125]

**Comment by boilerrat** [comment]
https://arbiscan.io/tx/0x5ce8b839c68f6e30d228d7d6e19964a6a7847c35a8ca68bf7d95b8f4e455f0e0



![Image](https://github.com/DAOmasons/grant-ships-app/assets/34731569/dc9503d3-e4c6-4c79-9d26-152df3f79956)

**Comment by boilerrat** [comment]
also made a post under updates. Transaction was good but subgraph timed out.



https://arbiscan.io/tx/0x91f7faa2b51ff12170af9adede84890491252f76434fd2fcfb614fb6a63cee51


![Image](https://github.com/DAOmasons/grant-ships-app/assets/34731569/966782a6-2bf4-4883-aaf7-2391f0127cfc)



![Image](https://github.com/DAOmasons/grant-ships-app/assets/34731569/3cf9a0be-79e4-40df-9c76-b4f81af8c2c4)

**Comment by jordanlesich** [comment]
Sometimes the subgraphs will time out. Especially on the testnets. Not much we can do about that.
