### ISSUE TITLE
Error:  Transaction submitting a milestone 2 failed

### ISSUE THREAD

**Issue by UI369** [DAOmasons/grant-ships-app#127]
https://arbiscan.io//tx/0x7999f144d8570698672d5bf03f009e03c1bb961a484d053357cda8a532787df8

![Image](https://github.com/DAOmasons/grant-ships-app/assets/84750997/559e4a4f-5242-4250-8924-c3bc37714a07)

**Comment by jordanlesich** [comment]
Out of gas issue. 

We might have to investigate gas estimation on Arbitrum. 

https://dashboard.tenderly.co/tx/arbitrum/0x7999f144d8570698672d5bf03f009e03c1bb961a484d053357cda8a532787df8
