### ISSUE TITLE
favicon in browser tab is too Dark to see. An Icon with a white back ground or change the color of the favicon to white.

### ISSUE THREAD

**Issue by boilerrat** [DAOmasons/grant-ships-app#139]

**Comment by boilerrat** [comment]
![Image](https://github.com/DAOmasons/grant-ships-app/assets/34731569/30b395ad-7676-4dd5-b9a2-3115f9365847)

**Comment by jordanlesich** [comment]
![Image](https://github.com/DAOmasons/grant-ships-app/assets/53406838/9eea8039-eafb-421c-ada3-f874440ebb15)
