### ISSUE TITLE
Give a UI Prompt on Grant Card when a new milestone has been submitted

### ISSUE THREAD

**Issue by UI369** [DAOmasons/grant-ships-app#145]
When a project applicant submits a milestone, they currently have to click on "View" to go to where the review milestone option is available.  Better option would be to put the review milestone button on the outer grant card.

Or put the View button on the Approved marker rather than leaving it on the previous step (which is already complete)

**Comment by UI369** [comment]
![Image](https://github.com/DAOmasons/grant-ships-app/assets/84750997/c25bcf89-be01-457f-95d8-7247b0306769)

**Comment by jordanlesich** [comment]
New build will not have Grant Cards. 

Closing for now.
