### ISSUE TITLE
Faciltiator communication w/Applicants

### ISSUE THREAD

**Issue by UI369** [DAOmasons/grant-ships-app#183]
As a Game Facilitator I'd like a way to send a message to project applicants and grant ship operators within the app. Currently I have to go to their contact info and choose one of the contact methods, and it isn't always the same.  

Some way to set up a templated or automatic communication when a project reaches a certain point in the process would be cool too.  For instance, a message w/KYC and Compliance policy attestation links could go to a project as soon as a Ship approves them for funding.

**Comment by jordanlesich** [comment]
Duplicate, will be solved with new Grants flow:

**Comment by jordanlesich** [comment]
Closing this now.
