### ISSUE TITLE
Link to application

### ISSUE THREAD

**Issue by UI369** [DAOmasons/grant-ships-app#195]
As a user I'd like to be able to link directly to a project's application.  Currently when I open the project application it doesn't change the URL so I can't share that app state externally. 

Example: https://app.grantships.fun/project/0xfecdcf6b7c12791707fa55f0d3baf216fadb561a

**Comment by jordanlesich** [comment]
We will solve this on the Grant page https://github.com/DAOmasons/grant-ships-app/issues/223. Closing for now
