### ISSUE TITLE
Nuance on total operator pot

### ISSUE THREAD

**Issue by UI369** [DAOmasons/grant-ships-app#204]
As a project I want know the approximate amount that the grant ship will fund. I see the total amount available but it would be silly for me to apply for that amount, but when I see that number I assume that's what I should apply for.  

- Supply a way for the operator to give the "nod" about what size grants the operator is willing to provide.

**Comment by jordanlesich** [comment]
Ship Operators should be able to have a pre-specified message that they send as part of the Grant flow.
