### ISSUE TITLE
Content for Milestone submission automatically posts update

### ISSUE THREAD

**Issue by UI369** [DAOmasons/grant-ships-app#206]
Rrrrrrr, [May 11, 2024 at 9:50:27 AM]:
We just posted an update here and I selected the grant (Blue Moon) but it doesn’t really show what the grant is for.
As a user it was strange that I just had to press ‘submit milestone’ and do the update in a different place (or I misunderstood the UX there, this was the only logical way I could figure how this would work)

(would be nice if the video was turned into a href as well), so you can click it (like here in case you’re interested: https://salmon-integral-fox-176.mypinata.cloud/ipfs/QmZ52yY9Mu4C3cPhVkRkHYbKT7o2ouywsLZPcxNtteVjry
)

![Image](https://github.com/DAOmasons/grant-ships-app/assets/84750997/e1db50aa-ca67-4af3-ac77-c6a8f1020c81)

**Comment by jordanlesich** [comment]
Sounds like a good feature to add to https://github.com/DAOmasons/grant-ships-app/issues/223.

**Comment by jordanlesich** [comment]
Need to decide if this happens on milestone completed or submitted.
