### ISSUE TITLE
As a Grant Ship Applicant when filling out Impact Thesis and Submission Guidelines I'd like to see informative placeholder text. (screenshot)

### ISSUE THREAD

**Issue by jordanlesich** [DAOmasons/grant-ships-app#25]
Currently both have "What is your ship's funding mission" for the placeholder text. 

![Image](https://github.com/DAOmasons/grant-ships-app/assets/84750997/a038c3ca-7820-4a82-ac4f-f698ace66057)

**Comment by jordanlesich** [comment]
@UI369 

Could I get you to write the placeholder text that you would like to see here?

**Comment by UI369** [comment]
@jordanlesich 

**Allocation Thesis**

What is your Ship's allocation thesis?

Include the types of projects prioritized, the desired impact of funding, and how grant effectiveness will be evaluated.


**Submission Guidelines**

What are your Ship's submission guidelines?

Include any screening criteria, requirements and agreements you will have for grant recipients.
