### ISSUE TITLE
As Grant Ship Operator - tried to approve an application and it gave me this error message.

### ISSUE THREAD

**Issue by UI369** [DAOmasons/grant-ships-app#57]
Tried again right away after and it worked fine.

![Image](https://github.com/DAOmasons/grant-ships-app/assets/84750997/908f8bac-826d-4ec6-91c4-5c0135d52faf)

**Comment by jordanlesich** [comment]
Interesting. Hard to deduce what's going on here. Let's keep tabs and if it happens again, bring it here.
