### ISSUE TITLE
As a Grants Ship Operator I want to know which ship I'm the administrator of

### ISSUE THREAD

**Issue by UI369** [DAOmasons/grant-ships-app#76]
Clicking my dashboard, I see a grant application but no indicator which ship I'm the operator of. 

![Image](https://github.com/DAOmasons/grant-ships-app/assets/84750997/9160d95f-c912-4eae-90fa-32f4ae83e89e)

"Approval from Grant Ship" is generic, not mentioning the Grant Ship Name. 

![Image](https://github.com/DAOmasons/grant-ships-app/assets/84750997/df8b56e3-3f7d-41e5-8df2-f833b8b033a1)

Grant Ships page shows 3 ships with identical interfaces, no indiicator which ship I'm the admin of.  
Each ship has "Members" but I am not a member listed.

![Image](https://github.com/DAOmasons/grant-ships-app/assets/84750997/7caf1eda-7ed7-443e-90da-42f08cad4903)

Suggested Fixes:

Add an indicator to the dashboard to show me which Grant Ship I'm the operator of
Add creating grant ship operator as a member of the grant ship. 
Put some indicator on the Grant Ships list if I am the operator or team member of one of them. (Operator should be a team member also)
Change grant approval/rejection message to show which Grant Ship is approving/rejecting

**Comment by jordanlesich** [comment]
![Image](https://github.com/DAOmasons/grant-ships-app/assets/53406838/eb099541-7cf8-4f85-8043-405b052d0797)

![Image](https://github.com/DAOmasons/grant-ships-app/assets/53406838/1619981f-0a37-4f7a-be75-aecfd0978c92)

![Image](https://github.com/DAOmasons/grant-ships-app/assets/53406838/c78eb793-848b-49f4-923e-3831233b0200)

![Image](https://github.com/DAOmasons/grant-ships-app/assets/53406838/9717b293-7109-40dd-9739-a798ffa65ee9)

Might need a better solution for the Ship cards, but will ship that for now.
