### ISSUE TITLE
Feed Tooltips

### ISSUE THREAD

**Issue by jordanlesich** [DAOmasons/grant-ships-app#80]
As any user I'd like to know what the little icons on the feed mean, maybe with a hover tooltip or legend somewhere

**Comment by jordanlesich** [comment]
Yep. Should also display a bigger avatar Tooltip when we hover over them.

**Comment by Sunjo22** [comment]
![Image](https://github.com/DAOmasons/grant-ships-app/assets/136875598/8d0255d5-04a5-405e-8d9f-621b4ce9f4d7)



![Image](https://github.com/DAOmasons/grant-ships-app/assets/136875598/db00aa4d-d124-485e-b9de-8f0300362e57)

**Comment by jordanlesich** [comment]
![Image](https://github.com/DAOmasons/grant-ships-app/assets/53406838/8633a274-cd2a-466d-8ab4-c1a33df7fe5d)



![Image](https://github.com/DAOmasons/grant-ships-app/assets/53406838/3ac1ad79-dce6-4292-8116-1630b2cfdd5f)
